<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="11" ignored="11" total="56" passed="25" failed="9" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-12-17T22:24:26 IST" name="MobilAppAutomation" finished-at="2024-12-18T02:10:09 IST" duration-ms="13543523">
    <groups>
    </groups>
    <test started-at="2024-12-17T22:24:26 IST" name="Default test" finished-at="2024-12-18T02:10:09 IST" duration-ms="13543523">
      <class name="sZephyr_testcases.TC22_DeviceSettings">
        <test-method retried="true" signature="removerepair()[pri:21, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:33:41 IST" name="removerepair" finished-at="2024-12-18T00:37:00 IST" duration-ms="198757" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:750)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC22_DeviceSettings.pairBlewithoutRouter(TC22_DeviceSettings.java:50)
at sZephyr_testcases.TC22_DeviceSettings.removerepair(TC22_DeviceSettings.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:33:41 IST" name="beforeMethod" finished-at="2024-12-18T00:33:41 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:33:41 IST" name="startTestCase" finished-at="2024-12-18T00:33:41 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:37:00 IST" name="afterMethod" finished-at="2024-12-18T00:37:04 IST" duration-ms="4394" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:37:04 IST" name="beforeMethod" finished-at="2024-12-18T00:37:04 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:21, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:37:04 IST" name="removerepair" finished-at="2024-12-18T00:40:22 IST" duration-ms="197551" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:750)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC22_DeviceSettings.pairBlewithoutRouter(TC22_DeviceSettings.java:50)
at sZephyr_testcases.TC22_DeviceSettings.removerepair(TC22_DeviceSettings.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@2bec854f]" started-at="2024-12-18T00:40:22 IST" name="afterMethod" finished-at="2024-12-18T00:40:26 IST" duration-ms="4341" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC22_DeviceSettings -->
      <class name="sZephyr_testcases.TC29_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC29_Schedular@6dd7b5a3]" started-at="2024-12-18T01:21:08 IST" name="startTestCase" finished-at="2024-12-18T01:21:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:28, instance:sZephyr_testcases.TC29_Schedular@6dd7b5a3]" started-at="2024-12-18T01:21:08 IST" name="schedule" finished-at="2024-12-18T01:36:03 IST" duration-ms="894675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC29_Schedular@6dd7b5a3]" started-at="2024-12-18T01:21:08 IST" name="beforeMethod" finished-at="2024-12-18T01:21:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC29_Schedular@6dd7b5a3]" started-at="2024-12-18T01:36:03 IST" name="afterMethod" finished-at="2024-12-18T01:36:09 IST" duration-ms="5652" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC29_Schedular -->
      <class name="sZephyr_testcases.TC02_SignUp">
        <test-method signature="signUp()[pri:1, instance:sZephyr_testcases.TC02_SignUp@56dc1551]" started-at="2024-12-17T22:28:37 IST" name="signUp" finished-at="2024-12-17T22:29:42 IST" duration-ms="64760" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@56dc1551]" started-at="2024-12-17T22:28:37 IST" name="beforeMethod" finished-at="2024-12-17T22:28:37 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC02_SignUp@56dc1551]" started-at="2024-12-17T22:28:37 IST" name="startTestCase" finished-at="2024-12-17T22:28:37 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@56dc1551]" started-at="2024-12-17T22:29:42 IST" name="afterMethod" finished-at="2024-12-17T22:29:44 IST" duration-ms="2569" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC02_SignUp -->
      <class name="sZephyr_testcases.TC03_SignUp">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC03_SignUp@102cec62]" started-at="2024-12-17T22:29:44 IST" name="startTestCase" finished-at="2024-12-17T22:29:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="signUp()[pri:2, instance:sZephyr_testcases.TC03_SignUp@102cec62]" started-at="2024-12-17T22:29:44 IST" name="signUp" finished-at="2024-12-17T22:30:43 IST" duration-ms="58847" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC03_SignUp@102cec62]" started-at="2024-12-17T22:29:44 IST" name="beforeMethod" finished-at="2024-12-17T22:29:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC03_SignUp@102cec62]" started-at="2024-12-17T22:30:43 IST" name="afterMethod" finished-at="2024-12-17T22:30:46 IST" duration-ms="2571" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC03_SignUp -->
      <class name="sZephyr_testcases.TC06_SignIn_SuccessFlow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@34b9f960]" started-at="2024-12-17T22:32:11 IST" name="startTestCase" finished-at="2024-12-17T22:32:11 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@34b9f960]" started-at="2024-12-17T22:32:11 IST" name="beforeMethod" finished-at="2024-12-17T22:32:11 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:5, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@34b9f960]" started-at="2024-12-17T22:32:11 IST" name="login" finished-at="2024-12-17T22:32:58 IST" duration-ms="47131" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@34b9f960]" started-at="2024-12-17T22:32:58 IST" name="afterMethod" finished-at="2024-12-17T22:33:00 IST" duration-ms="2104" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC06_SignIn_SuccessFlow -->
      <class name="sZephyr_testcases.TC17_WIfiWithout_router">
        <test-method retried="true" signature="removerepair()[pri:16, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:00:57 IST" name="removerepair" finished-at="2024-12-18T00:07:23 IST" duration-ms="386486" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC17_WIfiWithout_router.pairBlewithoutRouter(TC17_WIfiWithout_router.java:107)
at sZephyr_testcases.TC17_WIfiWithout_router.removerepair(TC17_WIfiWithout_router.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC17_WIfiWithout_router.pairBlewithoutRouter(TC17_WIfiWithout_router.java:68)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:00:57 IST" name="beforeMethod" finished-at="2024-12-18T00:00:57 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:00:57 IST" name="startTestCase" finished-at="2024-12-18T00:00:57 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:07:23 IST" name="afterMethod" finished-at="2024-12-18T00:07:27 IST" duration-ms="3615" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:16, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:07:27 IST" name="removerepair" finished-at="2024-12-18T00:13:52 IST" duration-ms="385570" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC17_WIfiWithout_router.pairBlewithoutRouter(TC17_WIfiWithout_router.java:107)
at sZephyr_testcases.TC17_WIfiWithout_router.removerepair(TC17_WIfiWithout_router.java:43)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC17_WIfiWithout_router.pairBlewithoutRouter(TC17_WIfiWithout_router.java:68)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:07:27 IST" name="beforeMethod" finished-at="2024-12-18T00:07:27 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@cd1e646]" started-at="2024-12-18T00:13:52 IST" name="afterMethod" finished-at="2024-12-18T00:13:56 IST" duration-ms="3517" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC17_WIfiWithout_router -->
      <class name="sZephyr_testcases.TC10_Pairing_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:50:02 IST" name="startTestCase" finished-at="2024-12-17T22:50:02 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="removerepair()[pri:9, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:50:02 IST" name="removerepair" finished-at="2024-12-17T22:54:20 IST" duration-ms="258249" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC10_Pairing_SmartConfig.removerepair(TC10_Pairing_SmartConfig.java:118)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC10_Pairing_SmartConfig.removerepair(TC10_Pairing_SmartConfig.java:56)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:50:02 IST" name="beforeMethod" finished-at="2024-12-17T22:50:02 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:54:20 IST" name="afterMethod" finished-at="2024-12-17T22:54:22 IST" duration-ms="2488" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:9, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:54:22 IST" name="removerepair" finished-at="2024-12-17T22:58:40 IST" duration-ms="257420" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC10_Pairing_SmartConfig.removerepair(TC10_Pairing_SmartConfig.java:118)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC10_Pairing_SmartConfig.removerepair(TC10_Pairing_SmartConfig.java:56)
... 26 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:54:22 IST" name="beforeMethod" finished-at="2024-12-17T22:54:22 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@30b6ffe0]" started-at="2024-12-17T22:58:40 IST" name="afterMethod" finished-at="2024-12-17T22:58:42 IST" duration-ms="2532" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC10_Pairing_SmartConfig -->
      <class name="sZephyr_testcases.TC04_SignIn_Flow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@74f6c5d8]" started-at="2024-12-17T22:30:46 IST" name="startTestCase" finished-at="2024-12-17T22:30:46 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="signIn()[pri:3, instance:sZephyr_testcases.TC04_SignIn_Flow@74f6c5d8]" started-at="2024-12-17T22:30:46 IST" name="signIn" finished-at="2024-12-17T22:31:15 IST" duration-ms="29376" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@74f6c5d8]" started-at="2024-12-17T22:30:46 IST" name="beforeMethod" finished-at="2024-12-17T22:30:46 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@74f6c5d8]" started-at="2024-12-17T22:31:15 IST" name="afterMethod" finished-at="2024-12-17T22:31:17 IST" duration-ms="2170" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC04_SignIn_Flow -->
      <class name="sZephyr_testcases.TC09_Pairing_BlewithRouter">
        <test-method signature="removerepair()[pri:8, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@4bbf6d0e]" started-at="2024-12-17T22:44:35 IST" name="removerepair" finished-at="2024-12-17T22:49:59 IST" duration-ms="323681" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@4bbf6d0e]" started-at="2024-12-17T22:44:35 IST" name="startTestCase" finished-at="2024-12-17T22:44:35 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@4bbf6d0e]" started-at="2024-12-17T22:44:35 IST" name="beforeMethod" finished-at="2024-12-17T22:44:35 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@4bbf6d0e]" started-at="2024-12-17T22:49:59 IST" name="afterMethod" finished-at="2024-12-17T22:50:02 IST" duration-ms="2482" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC09_Pairing_BlewithRouter -->
      <class name="sZephyr_testcases.TC01_Accounts_Info">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@3eb91815]" started-at="2024-12-17T22:24:26 IST" name="startTestCase" finished-at="2024-12-17T22:24:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@3eb91815]" started-at="2024-12-17T22:24:26 IST" name="beforeMethod" finished-at="2024-12-17T22:24:26 IST" duration-ms="4" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@3eb91815]" started-at="2024-12-17T22:24:26 IST" name="removerepair" finished-at="2024-12-17T22:28:35 IST" duration-ms="248989" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@3eb91815]" started-at="2024-12-17T22:28:35 IST" name="afterMethod" finished-at="2024-12-17T22:28:37 IST" duration-ms="2005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC01_Accounts_Info -->
      <class name="sZephyr_testcases.TC31_Schedular">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:44:39 IST" name="beforeMethod" finished-at="2024-12-18T01:44:39 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:44:39 IST" name="startTestCase" finished-at="2024-12-18T01:44:39 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="schedule()[pri:30, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:44:39 IST" name="schedule" finished-at="2024-12-18T01:46:06 IST" duration-ms="87222" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:657)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC31_Schedular.schedule(TC31_Schedular.java:63)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:46:06 IST" name="afterMethod" finished-at="2024-12-18T01:46:12 IST" duration-ms="5640" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="schedule()[pri:30, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:46:12 IST" name="schedule" finished-at="2024-12-18T02:00:06 IST" duration-ms="834284" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T01:46:12 IST" name="beforeMethod" finished-at="2024-12-18T01:46:12 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@2663e964]" started-at="2024-12-18T02:00:06 IST" name="afterMethod" finished-at="2024-12-18T02:00:12 IST" duration-ms="6204" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC31_Schedular -->
      <class name="sZephyr_testcases.TC23_Analytics">
        <test-method signature="removerepair()[pri:22, instance:sZephyr_testcases.TC23_Analytics@31edaa7d]" started-at="2024-12-18T00:40:26 IST" name="removerepair" finished-at="2024-12-18T00:44:04 IST" duration-ms="218049" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC23_Analytics@31edaa7d]" started-at="2024-12-18T00:40:26 IST" name="startTestCase" finished-at="2024-12-18T00:40:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC23_Analytics@31edaa7d]" started-at="2024-12-18T00:40:26 IST" name="beforeMethod" finished-at="2024-12-18T00:40:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC23_Analytics@31edaa7d]" started-at="2024-12-18T00:44:04 IST" name="afterMethod" finished-at="2024-12-18T00:44:08 IST" duration-ms="4438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC23_Analytics -->
      <class name="sZephyr_testcases.TC16_WifiWithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:46:57 IST" name="startTestCase" finished-at="2024-12-17T23:46:57 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="removerepair()[pri:15, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:46:57 IST" name="removerepair" finished-at="2024-12-17T23:53:48 IST" duration-ms="411514" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC16_WifiWithRouter.pairBlewithoutRouter(TC16_WifiWithRouter.java:104)
at sZephyr_testcases.TC16_WifiWithRouter.removerepair(TC16_WifiWithRouter.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC16_WifiWithRouter.pairBlewithoutRouter(TC16_WifiWithRouter.java:67)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:46:57 IST" name="beforeMethod" finished-at="2024-12-17T23:46:57 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:53:48 IST" name="afterMethod" finished-at="2024-12-17T23:53:52 IST" duration-ms="3850" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:15, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:53:52 IST" name="removerepair" finished-at="2024-12-18T00:00:43 IST" duration-ms="410763" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC16_WifiWithRouter.pairBlewithoutRouter(TC16_WifiWithRouter.java:104)
at sZephyr_testcases.TC16_WifiWithRouter.removerepair(TC16_WifiWithRouter.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC16_WifiWithRouter.pairBlewithoutRouter(TC16_WifiWithRouter.java:67)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-17T23:53:52 IST" name="beforeMethod" finished-at="2024-12-17T23:53:52 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@93081b6]" started-at="2024-12-18T00:00:43 IST" name="afterMethod" finished-at="2024-12-18T00:00:57 IST" duration-ms="13906" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC16_WifiWithRouter -->
      <class name="sZephyr_testcases.TC12_Pairing_WifiwithoutRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:06:57 IST" name="startTestCase" finished-at="2024-12-17T23:06:57 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="removerepair()[pri:11, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:06:57 IST" name="removerepair" finished-at="2024-12-17T23:10:17 IST" duration-ms="199804" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:750)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC12_Pairing_WifiwithoutRouter.removerepair(TC12_Pairing_WifiwithoutRouter.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:06:57 IST" name="beforeMethod" finished-at="2024-12-17T23:06:57 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:10:17 IST" name="afterMethod" finished-at="2024-12-17T23:10:19 IST" duration-ms="2584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:11, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:10:19 IST" name="removerepair" finished-at="2024-12-17T23:13:38 IST" duration-ms="199302" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:750)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC12_Pairing_WifiwithoutRouter.removerepair(TC12_Pairing_WifiwithoutRouter.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:10:19 IST" name="beforeMethod" finished-at="2024-12-17T23:10:19 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@2415fc55]" started-at="2024-12-17T23:13:38 IST" name="afterMethod" finished-at="2024-12-17T23:13:41 IST" duration-ms="2580" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC12_Pairing_WifiwithoutRouter -->
      <class name="sZephyr_testcases.TC05_SignIn_Valid_User">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@27912e3]" started-at="2024-12-17T22:31:17 IST" name="beforeMethod" finished-at="2024-12-17T22:31:17 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@27912e3]" started-at="2024-12-17T22:31:17 IST" name="startTestCase" finished-at="2024-12-17T22:31:17 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="login()[pri:4, instance:sZephyr_testcases.TC05_SignIn_Valid_User@27912e3]" started-at="2024-12-17T22:31:17 IST" name="login" finished-at="2024-12-17T22:32:08 IST" duration-ms="51121" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@27912e3]" started-at="2024-12-17T22:32:08 IST" name="afterMethod" finished-at="2024-12-17T22:32:11 IST" duration-ms="2213" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC05_SignIn_Valid_User -->
      <class name="sZephyr_testcases.TC19_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@1890516e]" started-at="2024-12-18T00:20:44 IST" name="startTestCase" finished-at="2024-12-18T00:20:44 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:18, instance:sZephyr_testcases.TC19_DeviceSettings@1890516e]" started-at="2024-12-18T00:20:44 IST" name="removerepair" finished-at="2024-12-18T00:25:09 IST" duration-ms="264857" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@1890516e]" started-at="2024-12-18T00:20:44 IST" name="beforeMethod" finished-at="2024-12-18T00:20:44 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@1890516e]" started-at="2024-12-18T00:25:09 IST" name="afterMethod" finished-at="2024-12-18T00:25:13 IST" duration-ms="3984" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC19_DeviceSettings -->
      <class name="sZephyr_testcases.TC14_BleWithRouter">
        <test-method signature="removerepair()[pri:13, instance:sZephyr_testcases.TC14_BleWithRouter@13bc8645]" started-at="2024-12-17T23:22:21 IST" name="removerepair" finished-at="2024-12-17T23:38:05 IST" duration-ms="944320" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@13bc8645]" started-at="2024-12-17T23:22:21 IST" name="beforeMethod" finished-at="2024-12-17T23:22:21 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@13bc8645]" started-at="2024-12-17T23:22:21 IST" name="startTestCase" finished-at="2024-12-17T23:22:21 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@13bc8645]" started-at="2024-12-17T23:38:05 IST" name="afterMethod" finished-at="2024-12-17T23:38:09 IST" duration-ms="3480" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC14_BleWithRouter -->
      <class name="sZephyr_testcases.TC25_Analytics">
        <test-method retried="true" signature="removerepair()[pri:24, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:48:25 IST" name="removerepair" finished-at="2024-12-18T00:53:23 IST" duration-ms="298709" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC25_Analytics.pairBlewithoutRouter(TC25_Analytics.java:78)
at sZephyr_testcases.TC25_Analytics.removerepair(TC25_Analytics.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.Analytics.navigateAnalyticsPage(Analytics.java:52)
at sZephyr_testcases.TC25_Analytics.pairBlewithoutRouter(TC25_Analytics.java:57)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:48:25 IST" name="startTestCase" finished-at="2024-12-18T00:48:25 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:48:25 IST" name="beforeMethod" finished-at="2024-12-18T00:48:25 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:53:23 IST" name="afterMethod" finished-at="2024-12-18T00:53:28 IST" duration-ms="4784" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:53:28 IST" name="beforeMethod" finished-at="2024-12-18T00:53:28 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:24, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:53:28 IST" name="removerepair" finished-at="2024-12-18T00:58:09 IST" duration-ms="281065" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@3336e6b6]" started-at="2024-12-18T00:58:09 IST" name="afterMethod" finished-at="2024-12-18T00:58:14 IST" duration-ms="4814" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC25_Analytics -->
      <class name="sZephyr_testcases.Longrun_voltvalue">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@456d6c1e]" started-at="2024-12-17T22:24:26 IST" name="beforeSuite" finished-at="2024-12-17T22:24:26 IST" duration-ms="286" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@456d6c1e]" started-at="2024-12-17T22:24:26 IST" name="beforeTest" finished-at="2024-12-17T22:24:26 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@456d6c1e]" started-at="2024-12-18T02:10:09 IST" name="afterTest" finished-at="2024-12-18T02:10:09 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@456d6c1e]" started-at="2024-12-18T02:10:10 IST" name="afterSuite" finished-at="2024-12-18T02:10:10 IST" duration-ms="240" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- sZephyr_testcases.Longrun_voltvalue -->
      <class name="sZephyr_testcases.TC34_sZephyr_Info">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@7bf3a5d8]" started-at="2024-12-18T02:06:54 IST" name="startTestCase" finished-at="2024-12-18T02:06:54 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:33, instance:sZephyr_testcases.TC34_sZephyr_Info@7bf3a5d8]" started-at="2024-12-18T02:06:54 IST" name="removerepair" finished-at="2024-12-18T02:10:03 IST" duration-ms="188956" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@7bf3a5d8]" started-at="2024-12-18T02:06:54 IST" name="beforeMethod" finished-at="2024-12-18T02:06:54 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@7bf3a5d8]" started-at="2024-12-18T02:10:03 IST" name="afterMethod" finished-at="2024-12-18T02:10:09 IST" duration-ms="6126" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC34_sZephyr_Info -->
      <class name="sZephyr_testcases.TC28_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC28_Schedular@6950ed69]" started-at="2024-12-18T01:12:38 IST" name="startTestCase" finished-at="2024-12-18T01:12:38 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:27, instance:sZephyr_testcases.TC28_Schedular@6950ed69]" started-at="2024-12-18T01:12:38 IST" name="schedule" finished-at="2024-12-18T01:21:03 IST" duration-ms="504925" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC28_Schedular@6950ed69]" started-at="2024-12-18T01:12:38 IST" name="beforeMethod" finished-at="2024-12-18T01:12:38 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC28_Schedular@6950ed69]" started-at="2024-12-18T01:21:03 IST" name="afterMethod" finished-at="2024-12-18T01:21:08 IST" duration-ms="5253" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC28_Schedular -->
      <class name="sZephyr_testcases.TC15_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:38:09 IST" name="startTestCase" finished-at="2024-12-17T23:38:09 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="removerepair()[pri:14, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:38:09 IST" name="removerepair" finished-at="2024-12-17T23:42:32 IST" duration-ms="263565" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC15_SmartConfig.pairBlewithoutRouter(TC15_SmartConfig.java:177)
at sZephyr_testcases.TC15_SmartConfig.removerepair(TC15_SmartConfig.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC15_SmartConfig.pairBlewithoutRouter(TC15_SmartConfig.java:66)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:38:09 IST" name="beforeMethod" finished-at="2024-12-17T23:38:09 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:42:32 IST" name="afterMethod" finished-at="2024-12-17T23:42:36 IST" duration-ms="3438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:14, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:42:36 IST" name="removerepair" finished-at="2024-12-17T23:46:53 IST" duration-ms="257291" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed due to this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed due to this exception
at org.testng.Assert.fail(Assert.java:99)
at sZephyr_testcases.TC15_SmartConfig.pairBlewithoutRouter(TC15_SmartConfig.java:177)
at sZephyr_testcases.TC15_SmartConfig.removerepair(TC15_SmartConfig.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: FAILED
at utils.Reporter.reportStep(Reporter.java:46)
at wrappers.GenericWrappers.clickbyXpath(GenericWrappers.java:204)
at pages.AddDevicePage.clickNextButtonsZephyrInfo(AddDevicePage.java:361)
at sZephyr_testcases.TC15_SmartConfig.pairBlewithoutRouter(TC15_SmartConfig.java:66)
... 27 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:42:36 IST" name="beforeMethod" finished-at="2024-12-17T23:42:36 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@24c22fe]" started-at="2024-12-17T23:46:53 IST" name="afterMethod" finished-at="2024-12-17T23:46:57 IST" duration-ms="3497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC15_SmartConfig -->
      <class name="sZephyr_testcases.TC33_Ble_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@189cbd7c]" started-at="2024-12-18T02:03:52 IST" name="startTestCase" finished-at="2024-12-18T02:03:52 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:32, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@189cbd7c]" started-at="2024-12-18T02:03:52 IST" name="removerepair" finished-at="2024-12-18T02:06:48 IST" duration-ms="176439" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@189cbd7c]" started-at="2024-12-18T02:03:52 IST" name="beforeMethod" finished-at="2024-12-18T02:03:52 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@189cbd7c]" started-at="2024-12-18T02:06:48 IST" name="afterMethod" finished-at="2024-12-18T02:06:54 IST" duration-ms="6141" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC33_Ble_Factory_Reset -->
      <class name="sZephyr_testcases.TC08_Pairing_BlewithoutRouter">
        <test-method signature="removerepair()[pri:7, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@19b89d4]" started-at="2024-12-17T22:36:13 IST" name="removerepair" finished-at="2024-12-17T22:44:33 IST" duration-ms="500022" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@19b89d4]" started-at="2024-12-17T22:36:13 IST" name="beforeMethod" finished-at="2024-12-17T22:36:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@19b89d4]" started-at="2024-12-17T22:36:13 IST" name="startTestCase" finished-at="2024-12-17T22:36:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@19b89d4]" started-at="2024-12-17T22:44:33 IST" name="afterMethod" finished-at="2024-12-17T22:44:35 IST" duration-ms="2391" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC08_Pairing_BlewithoutRouter -->
      <class name="sZephyr_testcases.TC20_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@15a04efb]" started-at="2024-12-18T00:25:13 IST" name="startTestCase" finished-at="2024-12-18T00:25:13 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:19, instance:sZephyr_testcases.TC20_DeviceSettings@15a04efb]" started-at="2024-12-18T00:25:13 IST" name="removerepair" finished-at="2024-12-18T00:29:46 IST" duration-ms="273230" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@15a04efb]" started-at="2024-12-18T00:25:13 IST" name="beforeMethod" finished-at="2024-12-18T00:25:13 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@15a04efb]" started-at="2024-12-18T00:29:46 IST" name="afterMethod" finished-at="2024-12-18T00:29:50 IST" duration-ms="4165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC20_DeviceSettings -->
      <class name="sZephyr_testcases.TC13_BlewithoutRouter">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:13:41 IST" name="beforeMethod" finished-at="2024-12-17T23:13:41 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:13:41 IST" name="startTestCase" finished-at="2024-12-17T23:13:41 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method retried="true" signature="removerepair()[pri:12, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:13:41 IST" name="removerepair" finished-at="2024-12-17T23:15:13 IST" duration-ms="92289" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:657)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC13_BlewithoutRouter.pairBlewithoutRouter(TC13_BlewithoutRouter.java:67)
at sZephyr_testcases.TC13_BlewithoutRouter.removerepair(TC13_BlewithoutRouter.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:15:13 IST" name="afterMethod" finished-at="2024-12-17T23:15:16 IST" duration-ms="2572" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:15:16 IST" name="beforeMethod" finished-at="2024-12-17T23:15:16 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:12, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:15:16 IST" name="removerepair" finished-at="2024-12-17T23:22:18 IST" duration-ms="422423" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:657)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC13_BlewithoutRouter.pairBlewithoutRouter(TC13_BlewithoutRouter.java:127)
at sZephyr_testcases.TC13_BlewithoutRouter.removerepair(TC13_BlewithoutRouter.java:45)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@14f232c4]" started-at="2024-12-17T23:22:18 IST" name="afterMethod" finished-at="2024-12-17T23:22:21 IST" duration-ms="2781" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC13_BlewithoutRouter -->
      <class name="sZephyr_testcases.TC07_SignIn_Logout">
        <test-method signature="login()[pri:6, instance:sZephyr_testcases.TC07_SignIn_Logout@43015c69]" started-at="2024-12-17T22:33:00 IST" name="login" finished-at="2024-12-17T22:36:11 IST" duration-ms="190963" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@43015c69]" started-at="2024-12-17T22:33:00 IST" name="startTestCase" finished-at="2024-12-17T22:33:00 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@43015c69]" started-at="2024-12-17T22:33:00 IST" name="beforeMethod" finished-at="2024-12-17T22:33:00 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@43015c69]" started-at="2024-12-17T22:36:11 IST" name="afterMethod" finished-at="2024-12-17T22:36:13 IST" duration-ms="2195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC07_SignIn_Logout -->
      <class name="sZephyr_testcases.TC27_Analytics">
        <test-method retried="true" signature="removerepair()[pri:26, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:03:39 IST" name="removerepair" finished-at="2024-12-18T01:08:22 IST" duration-ms="283323" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:718)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:791)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC27_Analytics.pairBlewithoutRouter(TC27_Analytics.java:48)
at sZephyr_testcases.TC27_Analytics.removerepair(TC27_Analytics.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:03:39 IST" name="beforeMethod" finished-at="2024-12-18T01:03:39 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:03:39 IST" name="startTestCase" finished-at="2024-12-18T01:03:39 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:08:22 IST" name="afterMethod" finished-at="2024-12-18T01:08:27 IST" duration-ms="5119" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:26, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:08:27 IST" name="removerepair" finished-at="2024-12-18T01:12:33 IST" duration-ms="245704" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:718)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC27_Analytics.pairBlewithoutRouter(TC27_Analytics.java:48)
at sZephyr_testcases.TC27_Analytics.removerepair(TC27_Analytics.java:31)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:08:27 IST" name="beforeMethod" finished-at="2024-12-18T01:08:27 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@205d38da]" started-at="2024-12-18T01:12:33 IST" name="afterMethod" finished-at="2024-12-18T01:12:38 IST" duration-ms="5125" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC27_Analytics -->
      <class name="sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03">
        <test-method signature="removerepair()[pri:17, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@7ba8c737]" started-at="2024-12-18T00:13:56 IST" name="removerepair" finished-at="2024-12-18T00:20:40 IST" duration-ms="404370" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@7ba8c737]" started-at="2024-12-18T00:13:56 IST" name="beforeMethod" finished-at="2024-12-18T00:13:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@7ba8c737]" started-at="2024-12-18T00:13:56 IST" name="startTestCase" finished-at="2024-12-18T00:13:56 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@7ba8c737]" started-at="2024-12-18T00:20:40 IST" name="afterMethod" finished-at="2024-12-18T00:20:44 IST" duration-ms="3804" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03 -->
      <class name="sZephyr_testcases.TC30_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC30_Schedular@6f3187b0]" started-at="2024-12-18T01:36:09 IST" name="startTestCase" finished-at="2024-12-18T01:36:09 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC30_Schedular@6f3187b0]" started-at="2024-12-18T01:36:09 IST" name="beforeMethod" finished-at="2024-12-18T01:36:09 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="schedule()[pri:29, instance:sZephyr_testcases.TC30_Schedular@6f3187b0]" started-at="2024-12-18T01:36:09 IST" name="schedule" finished-at="2024-12-18T01:44:33 IST" duration-ms="504518" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC30_Schedular@6f3187b0]" started-at="2024-12-18T01:44:33 IST" name="afterMethod" finished-at="2024-12-18T01:44:39 IST" duration-ms="6009" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC30_Schedular -->
      <class name="sZephyr_testcases.TC24_Analytics">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC24_Analytics@26adfd2d]" started-at="2024-12-18T00:44:08 IST" name="beforeMethod" finished-at="2024-12-18T00:44:08 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC24_Analytics@26adfd2d]" started-at="2024-12-18T00:44:08 IST" name="startTestCase" finished-at="2024-12-18T00:44:08 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:23, instance:sZephyr_testcases.TC24_Analytics@26adfd2d]" started-at="2024-12-18T00:44:08 IST" name="removerepair" finished-at="2024-12-18T00:48:20 IST" duration-ms="251709" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC24_Analytics@26adfd2d]" started-at="2024-12-18T00:48:20 IST" name="afterMethod" finished-at="2024-12-18T00:48:25 IST" duration-ms="4554" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC24_Analytics -->
      <class name="sZephyr_testcases.TC11_Pairing_WifiwithRouter">
        <test-method retried="true" signature="removerepair()[pri:10, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T22:58:42 IST" name="removerepair" finished-at="2024-12-17T23:02:48 IST" duration-ms="246049" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:718)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC11_Pairing_WifiwithRouter.removerepair(TC11_Pairing_WifiwithRouter.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T22:58:42 IST" name="startTestCase" finished-at="2024-12-17T22:58:42 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T22:58:42 IST" name="beforeMethod" finished-at="2024-12-17T22:58:42 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T23:02:48 IST" name="afterMethod" finished-at="2024-12-17T23:02:51 IST" duration-ms="2556" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="removerepair()[pri:10, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T23:02:51 IST" name="removerepair" finished-at="2024-12-17T23:06:54 IST" duration-ms="243277" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.fail(Assert.java:116)
at pages.AddDevicePage.retrypagecheck(AddDevicePage.java:854)
at pages.AddDevicePage.proceedToAddDevice(AddDevicePage.java:718)
at pages.AddDevicePage.initiatepairing(AddDevicePage.java:628)
at pages.AddDevicePage.pair(AddDevicePage.java:584)
at sZephyr_testcases.TC11_Pairing_WifiwithRouter.removerepair(TC11_Pairing_WifiwithRouter.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T23:02:51 IST" name="beforeMethod" finished-at="2024-12-17T23:02:51 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@791d1f8b]" started-at="2024-12-17T23:06:54 IST" name="afterMethod" finished-at="2024-12-17T23:06:57 IST" duration-ms="2549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC11_Pairing_WifiwithRouter -->
      <class name="sZephyr_testcases.TC32_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@48b67364]" started-at="2024-12-18T02:00:12 IST" name="startTestCase" finished-at="2024-12-18T02:00:12 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:31, instance:sZephyr_testcases.TC32_Factory_Reset@48b67364]" started-at="2024-12-18T02:00:12 IST" name="removerepair" finished-at="2024-12-18T02:03:46 IST" duration-ms="213373" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@48b67364]" started-at="2024-12-18T02:00:12 IST" name="beforeMethod" finished-at="2024-12-18T02:00:12 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@48b67364]" started-at="2024-12-18T02:03:46 IST" name="afterMethod" finished-at="2024-12-18T02:03:52 IST" duration-ms="6014" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC32_Factory_Reset -->
      <class name="sZephyr_testcases.TC21_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@16c069df]" started-at="2024-12-18T00:29:50 IST" name="startTestCase" finished-at="2024-12-18T00:29:50 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:20, instance:sZephyr_testcases.TC21_DeviceSettings@16c069df]" started-at="2024-12-18T00:29:50 IST" name="removerepair" finished-at="2024-12-18T00:33:37 IST" duration-ms="226378" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@16c069df]" started-at="2024-12-18T00:29:50 IST" name="beforeMethod" finished-at="2024-12-18T00:29:50 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@16c069df]" started-at="2024-12-18T00:33:37 IST" name="afterMethod" finished-at="2024-12-18T00:33:41 IST" duration-ms="4267" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC21_DeviceSettings -->
      <class name="sZephyr_testcases.TC26_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC26_Analytics@7c3fdb62]" started-at="2024-12-18T00:58:14 IST" name="startTestCase" finished-at="2024-12-18T00:58:14 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC26_Analytics@7c3fdb62]" started-at="2024-12-18T00:58:14 IST" name="beforeMethod" finished-at="2024-12-18T00:58:14 IST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:25, instance:sZephyr_testcases.TC26_Analytics@7c3fdb62]" started-at="2024-12-18T00:58:14 IST" name="removerepair" finished-at="2024-12-18T01:03:34 IST" duration-ms="319608" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC26_Analytics@7c3fdb62]" started-at="2024-12-18T01:03:34 IST" name="afterMethod" finished-at="2024-12-18T01:03:39 IST" duration-ms="5021" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC26_Analytics -->
    </test> <!-- Default test -->
  </suite> <!-- MobilAppAutomation -->
</testng-results>
