<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="35" passed="0" failed="0" skipped="35">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-02T17:06:45 IST" name="Suite" finished-at="2025-05-02T17:06:45 IST" duration-ms="186">
    <groups>
    </groups>
    <test started-at="2025-05-02T17:06:45 IST" name="Test" finished-at="2025-05-02T17:06:45 IST" duration-ms="186">
      <class name="sZephyr_testcases.TC22_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@25084a1e]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:21, instance:sZephyr_testcases.TC22_DeviceSettings@25084a1e]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@25084a1e]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC22_DeviceSettings@25084a1e]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC22_DeviceSettings -->
      <class name="sZephyr_testcases.TC29_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC29_Schedular@53fdffa1]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:28, instance:sZephyr_testcases.TC29_Schedular@53fdffa1]" started-at="2025-05-02T17:06:45 IST" name="schedule" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC29_Schedular@53fdffa1]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC29_Schedular@53fdffa1]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC29_Schedular -->
      <class name="sZephyr_testcases.TC02_SignUp">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC02_SignUp@28f3b248]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@28f3b248]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUp()[pri:1, instance:sZephyr_testcases.TC02_SignUp@28f3b248]" started-at="2025-05-02T17:06:45 IST" name="signUp" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC02_SignUp@28f3b248]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC02_SignUp -->
      <class name="sZephyr_testcases.TC03_SignUp">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC03_SignUp@1b1426f4]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC03_SignUp@1b1426f4]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signUp()[pri:2, instance:sZephyr_testcases.TC03_SignUp@1b1426f4]" started-at="2025-05-02T17:06:45 IST" name="signUp" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signUp -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC03_SignUp@1b1426f4]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC03_SignUp -->
      <class name="sZephyr_testcases.TC06_SignIn_SuccessFlow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@6d4e5011]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@6d4e5011]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:5, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@6d4e5011]" started-at="2025-05-02T17:06:45 IST" name="login" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC06_SignIn_SuccessFlow@6d4e5011]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC06_SignIn_SuccessFlow -->
      <class name="sZephyr_testcases.TC17_WIfiWithout_router">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@3d6f0054]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:16, instance:sZephyr_testcases.TC17_WIfiWithout_router@3d6f0054]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@3d6f0054]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC17_WIfiWithout_router@3d6f0054]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC17_WIfiWithout_router -->
      <class name="sZephyr_testcases.TC10_Pairing_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@67c33749]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:9, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@67c33749]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@67c33749]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC10_Pairing_SmartConfig@67c33749]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC10_Pairing_SmartConfig -->
      <class name="sZephyr_testcases.TC04_SignIn_Flow">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@32b260fa]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@32b260fa]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="signIn()[pri:3, instance:sZephyr_testcases.TC04_SignIn_Flow@32b260fa]" started-at="2025-05-02T17:06:45 IST" name="signIn" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- signIn -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC04_SignIn_Flow@32b260fa]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC04_SignIn_Flow -->
      <class name="sZephyr_testcases.TC09_Pairing_BlewithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@78123e82]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@78123e82]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:8, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@78123e82]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC09_Pairing_BlewithRouter@78123e82]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC09_Pairing_BlewithRouter -->
      <class name="sZephyr_testcases.TC01_Accounts_Info">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@63a12c68]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@63a12c68]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@63a12c68]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC01_Accounts_Info@63a12c68]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC01_Accounts_Info -->
      <class name="sZephyr_testcases.TC31_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC31_Schedular@32ee6fee]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:30, instance:sZephyr_testcases.TC31_Schedular@32ee6fee]" started-at="2025-05-02T17:06:45 IST" name="schedule" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@32ee6fee]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC31_Schedular@32ee6fee]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC31_Schedular -->
      <class name="sZephyr_testcases.TC23_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC23_Analytics@156b88f5]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:22, instance:sZephyr_testcases.TC23_Analytics@156b88f5]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC23_Analytics@156b88f5]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC23_Analytics@156b88f5]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC23_Analytics -->
      <class name="sZephyr_testcases.TC16_WifiWithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@16a0ee18]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@16a0ee18]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:15, instance:sZephyr_testcases.TC16_WifiWithRouter@16a0ee18]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC16_WifiWithRouter@16a0ee18]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC16_WifiWithRouter -->
      <class name="sZephyr_testcases.TC12_Pairing_WifiwithoutRouter">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@662b4c69]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@662b4c69]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:11, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@662b4c69]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC12_Pairing_WifiwithoutRouter@662b4c69]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC12_Pairing_WifiwithoutRouter -->
      <class name="sZephyr_testcases.TC05_SignIn_Valid_User">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@581ac8a8]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@581ac8a8]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:4, instance:sZephyr_testcases.TC05_SignIn_Valid_User@581ac8a8]" started-at="2025-05-02T17:06:45 IST" name="login" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC05_SignIn_Valid_User@581ac8a8]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC05_SignIn_Valid_User -->
      <class name="sZephyr_testcases.TC19_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@5fbdfdcf]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:18, instance:sZephyr_testcases.TC19_DeviceSettings@5fbdfdcf]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@5fbdfdcf]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC19_DeviceSettings@5fbdfdcf]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC19_DeviceSettings -->
      <class name="sZephyr_testcases.TC14_BleWithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@71238fc2]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@71238fc2]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:13, instance:sZephyr_testcases.TC14_BleWithRouter@71238fc2]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC14_BleWithRouter@71238fc2]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC14_BleWithRouter -->
      <class name="sZephyr_testcases.TC25_Analytics">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@16610890]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC25_Analytics@16610890]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:24, instance:sZephyr_testcases.TC25_Analytics@16610890]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC25_Analytics@16610890]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC25_Analytics -->
      <class name="sZephyr_testcases.Longrun_voltvalue">
        <test-method is-config="true" signature="beforeSuite()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@10feca44]" started-at="2025-05-02T17:06:45 IST" name="beforeSuite" finished-at="2025-05-02T17:06:45 IST" duration-ms="313" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method is-config="true" signature="beforeTest()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@10feca44]" started-at="2025-05-02T17:06:45 IST" name="beforeTest" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method is-config="true" signature="afterTest()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@10feca44]" started-at="2025-05-02T17:06:45 IST" name="afterTest" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method is-config="true" signature="afterSuite()[pri:0, instance:sZephyr_testcases.Longrun_voltvalue@10feca44]" started-at="2025-05-02T17:06:45 IST" name="afterSuite" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- sZephyr_testcases.Longrun_voltvalue -->
      <class name="sZephyr_testcases.TC34_sZephyr_Info">
        <test-method signature="removerepair()[pri:33, instance:sZephyr_testcases.TC34_sZephyr_Info@3232a28a]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@3232a28a]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@3232a28a]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC34_sZephyr_Info@3232a28a]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC34_sZephyr_Info -->
      <class name="sZephyr_testcases.TC28_Schedular">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC28_Schedular@4d465b11]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC28_Schedular@4d465b11]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:27, instance:sZephyr_testcases.TC28_Schedular@4d465b11]" started-at="2025-05-02T17:06:45 IST" name="schedule" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC28_Schedular@4d465b11]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC28_Schedular -->
      <class name="sZephyr_testcases.TC33_Ble_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@7133da86]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:32, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@7133da86]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@7133da86]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC33_Ble_Factory_Reset@7133da86]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC33_Ble_Factory_Reset -->
      <class name="sZephyr_testcases.TC15_SmartConfig">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@2a54a73f]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:14, instance:sZephyr_testcases.TC15_SmartConfig@2a54a73f]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@2a54a73f]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC15_SmartConfig@2a54a73f]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC15_SmartConfig -->
      <class name="sZephyr_testcases.TC08_Pairing_BlewithoutRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@76c3e77a]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@76c3e77a]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:7, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@76c3e77a]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC08_Pairing_BlewithoutRouter@76c3e77a]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC08_Pairing_BlewithoutRouter -->
      <class name="sZephyr_testcases.TC20_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@4efc180e]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@4efc180e]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:19, instance:sZephyr_testcases.TC20_DeviceSettings@4efc180e]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC20_DeviceSettings@4efc180e]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC20_DeviceSettings -->
      <class name="sZephyr_testcases.TC13_BlewithoutRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@fa49800]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:12, instance:sZephyr_testcases.TC13_BlewithoutRouter@fa49800]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@fa49800]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC13_BlewithoutRouter@fa49800]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC13_BlewithoutRouter -->
      <class name="sZephyr_testcases.TC07_SignIn_Logout">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@57d7f8ca]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@57d7f8ca]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="login()[pri:6, instance:sZephyr_testcases.TC07_SignIn_Logout@57d7f8ca]" started-at="2025-05-02T17:06:45 IST" name="login" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC07_SignIn_Logout@57d7f8ca]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC07_SignIn_Logout -->
      <class name="sZephyr_testcases.TC27_Analytics">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@383bfa16]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC27_Analytics@383bfa16]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:26, instance:sZephyr_testcases.TC27_Analytics@383bfa16]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC27_Analytics@383bfa16]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC27_Analytics -->
      <class name="sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@505fc5a4]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:17, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@505fc5a4]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@505fc5a4]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03@505fc5a4]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC18_UI_CONNECTIVITY_MOD_0_TC_01_TO_03 -->
      <class name="sZephyr_testcases.TC30_Schedular">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC30_Schedular@5562c41e]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="schedule()[pri:29, instance:sZephyr_testcases.TC30_Schedular@5562c41e]" started-at="2025-05-02T17:06:45 IST" name="schedule" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- schedule -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC30_Schedular@5562c41e]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC30_Schedular@5562c41e]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC30_Schedular -->
      <class name="sZephyr_testcases.TC24_Analytics">
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC24_Analytics@3bf9ce3e]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC24_Analytics@3bf9ce3e]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:23, instance:sZephyr_testcases.TC24_Analytics@3bf9ce3e]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC24_Analytics@3bf9ce3e]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC24_Analytics -->
      <class name="sZephyr_testcases.TC11_Pairing_WifiwithRouter">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@fba92d3]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:10, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@fba92d3]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@fba92d3]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC11_Pairing_WifiwithRouter@fba92d3]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC11_Pairing_WifiwithRouter -->
      <class name="sZephyr_testcases.TC32_Factory_Reset">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@4d0f2471]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@4d0f2471]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="removerepair()[pri:31, instance:sZephyr_testcases.TC32_Factory_Reset@4d0f2471]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC32_Factory_Reset@4d0f2471]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC32_Factory_Reset -->
      <class name="sZephyr_testcases.TC21_DeviceSettings">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@bd4dc25]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:20, instance:sZephyr_testcases.TC21_DeviceSettings@bd4dc25]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@bd4dc25]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC21_DeviceSettings@bd4dc25]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC21_DeviceSettings -->
      <class name="sZephyr_testcases.TC26_Analytics">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC26_Analytics@71def8f8]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="removerepair()[pri:25, instance:sZephyr_testcases.TC26_Analytics@71def8f8]" started-at="2025-05-02T17:06:45 IST" name="removerepair" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- removerepair -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC26_Analytics@71def8f8]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC26_Analytics@71def8f8]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC26_Analytics -->
      <class name="sZephyr_testcases.TC36_ESMmode">
        <test-method is-config="true" signature="startTestCase()[pri:0, instance:sZephyr_testcases.TC36_ESMmode@47faa49c]" started-at="2025-05-02T17:06:45 IST" name="startTestCase" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startTestCase -->
        <test-method signature="pairBlewithoutRouter()[pri:34, instance:sZephyr_testcases.TC36_ESMmode@47faa49c]" started-at="2025-05-02T17:06:45 IST" name="pairBlewithoutRouter" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[ADB device check failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: ADB device check failed
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1033)
at wrappers.MobileAppWrappers.beforeSuite(MobileAppWrappers.java:79)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:393)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:326)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1228)
at org.testng.TestNG.runSuites(TestNG.java:1134)
at org.testng.TestNG.run(TestNG.java:1101)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.RuntimeException: No ADB devices connected. Test execution stopped.
at wrappers.GenericWrappers.ABDconnection(GenericWrappers.java:1020)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- pairBlewithoutRouter -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:sZephyr_testcases.TC36_ESMmode@47faa49c]" started-at="2025-05-02T17:06:45 IST" name="beforeMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method is-config="true" signature="afterMethod()[pri:0, instance:sZephyr_testcases.TC36_ESMmode@47faa49c]" started-at="2025-05-02T17:06:45 IST" name="afterMethod" finished-at="2025-05-02T17:06:45 IST" duration-ms="0" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- sZephyr_testcases.TC36_ESMmode -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
